[build]
  functions = "functions"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "vite"
  targetPort = 8080
  port = 8888
  autoLaunch = true
