[build]
  functions = "functions"
  publish = "dist"
  command = "npm run build"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Admin pages
[[redirects]]
  from = "/admin"
  to = "/admin/simple-github.html"
  status = 200

[[redirects]]
  from = "/admin-direct"
  to = "/admin/direct-github.html"
  status = 200

[[redirects]]
  from = "/admin-simple"
  to = "/admin/simple.html"
  status = 200

[[redirects]]
  from = "/admin-github"
  to = "/admin/simple-github.html"
  status = 200

# Specific routes for common pages
[[redirects]]
  from = "/shop"
  to = "/shop/index.html"
  status = 200

[[redirects]]
  from = "/product/*"
  to = "/product/index.html"
  status = 200

[[redirects]]
  from = "/bag"
  to = "/bag/index.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout/index.html"
  status = 200

# Support client-side routing - this must come before the 404 redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Path = {exclude = ["/admin/*", "/api/*"]}}

# Custom 404 page - this should come after the client-side routing redirect
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
