# This file is used to configure environment variables for Netlify
# Run: netlify env:import netlify.env.toml

[build.environment]
  # GitHub configuration
  GITHUB_OWNER = "kevinabouhanna"
  GITHUB_REPO = "Omnis"
  # Don't include GITHUB_TOKEN here for security reasons
  
  # Netlify site URL
  URL = "https://omnis-lb.netlify.app"
  
  # Don't include Mailjet credentials here for security reasons
  # Add them manually in the Netlify dashboard
