# This file is used to configure environment variables for Netlify
# Run: netlify env:import netlify.env.toml

[build.environment]
  # GitHub configuration
  GITHUB_OWNER = "kevinabouhanna"
  GITHUB_REPO = "Omnis"
  # Don't include GITHUB_TOKEN here for security reasons

  # Netlify site URL
  URL = "https://omnis-lb.netlify.app"

  # Don't include Resend API key here for security reasons
  # Add it manually in the Netlify dashboard

  VITE_SUPABASE_URL=https://cjttmpflrqacbrkxzfcs.supabase.co
  VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdHRtcGZscnFhY2Jya3h6ZmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjU1MzYsImV4cCI6MjA2Mjc0MTUzNn0.JkzGTF-6y_xQzG48Ey_l_XuX2-s4_xANZ0a1Bi7VdIY
